# Generated by Django 3.2.12 on 2022-06-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_alter_park_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='tag',
            field=models.ManyToManyField(blank=True, to='sns.Tag', verbose_name='タグ'),
        ),
    ]
