# Generated by Django 3.2.12 on 2022-07-28 06:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0004_alter_park_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, verbose_name='コメント')),
                ('star', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='星の数')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns.park', verbose_name='レビュー対象の公園')),
            ],
        ),
    ]
