# Generated by Django 3.2.12 on 2022-07-28 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時'),
        ),
    ]
